## BA5A
### Find mininum number of coins needed to make change 

In [3]:
# Solved
def minCoins_for_change(money, coins):
    coin_count = [0]*(money+1)
    for m in range(1, money+1):
        coin_count[m] = min(coin_count[m-coin]+1 for coin in coins if m>=coin )
    return coin_count[money]
#     for m in range(1, money+1):
#         mn = 10000000000
#         for coin in coins:
#             if(m >= coin):
#                 mn = min(mn, coin_count[m-coin] + 1)
#         coin_count[m] = mn
#     return coin_count[money]


money = 40
coins = [1,5,10,20,25,50]
money = 17903
coins = [1,3,5,9,10,11,20,22]

minCoins_for_change(money, coins)

815

In [ ]:
def min_coin()

## BA5B
### Longest path in the manhatton tourist problem 

In [49]:
import numpy as np

def longest_path_manhatton(down, right, n, m):
    scores = np.zeros([n+1,m+1], dtype = int)
#     print(scores)
    scores[1:, 0] = np.cumsum(down[:, 0])
    scores[0, 1:] = np.cumsum(right[0, :])
    print(scores)
    for i in range(1, n+1):
        for j in range(1, m+1):
            scores[i,j] = max(scores[i-1,j] + down[i-1,j] , scores[i,j-1] + right[i,j-1])
    
    print(scores)
    
    return scores[n,m]
down_str = '''1 0 2 4 3
4 6 5 2 1
4 4 5 2 1
5 6 8 5 3'''

right_str = '''3 2 4 0
3 2 4 2
0 7 3 3
3 3 0 2
1 3 2 2'''
n,m = 4,4
# n,m = 14,14
# down_str = '''3 1 3 2 1 1 0 2 1 2 2 4 3 3 3
# 2 2 3 3 2 4 4 0 1 1 2 3 2 0 2
# 4 0 0 1 2 3 2 2 4 1 1 1 4 2 0
# 2 3 3 3 1 3 4 4 3 1 2 3 0 2 4
# 4 3 2 2 2 1 4 4 3 1 0 3 0 1 2
# 2 1 4 0 4 4 2 2 0 4 0 4 4 3 4
# 3 2 2 1 0 4 1 1 4 2 3 3 0 1 0
# 0 4 0 1 2 0 4 1 0 2 2 3 4 2 3
# 0 1 3 1 2 4 3 1 1 2 4 3 4 0 3
# 3 4 3 4 2 2 3 2 4 0 2 2 3 4 2
# 3 1 2 0 2 1 0 2 3 2 3 0 1 1 0
# 3 3 3 0 3 3 3 2 0 1 3 1 4 2 4
# 2 3 3 1 0 4 2 0 4 3 4 3 4 3 4
# 4 4 1 0 4 0 2 0 0 4 3 4 3 3 1'''
# right_str = '''4 0 4 0 2 4 0 2 2 2 4 0 2 0
# 4 4 1 0 4 3 1 1 0 3 4 4 0 0
# 3 3 1 4 2 2 0 3 0 0 3 2 0 1
# 1 1 2 2 4 1 4 4 3 3 3 1 3 4
# 2 2 0 1 2 3 3 3 3 2 4 1 4 3
# 1 1 0 0 0 1 4 1 1 2 1 3 0 2
# 3 2 4 0 3 4 1 3 2 4 4 3 3 1
# 3 0 3 1 2 3 0 1 0 3 0 2 3 3
# 1 1 1 2 2 2 1 3 3 1 1 2 1 2
# 0 4 1 0 1 0 4 2 4 0 3 4 1 4
# 4 3 1 3 3 3 0 4 3 2 0 1 4 2
# 2 3 1 1 2 4 3 2 2 2 2 4 1 0
# 4 4 1 2 0 0 3 0 1 4 3 0 0 4
# 3 0 1 2 4 4 0 3 2 0 0 4 4 0
# 3 1 1 2 3 2 3 4 4 0 4 3 4 3
# '''
down_matrix = np.fromstring(down_str, dtype = int, sep = ' ').reshape(n,m+1)
right_matrix = np.fromstring(right_str, dtype=int, sep = ' ').reshape(n+1,m)
print(down_matrix, '\n', right_matrix)
longest_path_manhatton(down_matrix, right_matrix, n,m)


[[1 0 2 4 3]
 [4 6 5 2 1]
 [4 4 5 2 1]
 [5 6 8 5 3]] 
 [[3 2 4 0]
 [3 2 4 2]
 [0 7 3 3]
 [3 3 0 2]
 [1 3 2 2]]
[[ 0  3  5  9  9]
 [ 1  0  0  0  0]
 [ 5  0  0  0  0]
 [ 9  0  0  0  0]
 [14  0  0  0  0]]
[[ 0  3  5  9  9]
 [ 1  4  7 13 15]
 [ 5 10 17 20 23]
 [ 9 14 22 22 24]
 [14 20 30 32 34]]


34

In [13]:
import numpy as np

def longest_path(n,m,down,right): 
    path = np.zeros([n+1,m+1], dtype = int)
    
    path[1:,0] = np.cumsum(down[:, 0])
    path[0,1:] = np.cumsum(right[0,:])
    print(path)
    for i in range(1,n+1):
        for j in range(1,m+1):
            path[i][j] = max(path[i][j-1]+right[i][j-1], path[i-1][j]+down[i-1][j])
    
    return path[n,m]
n,m = 4,4
down_str = '''1 0 2 4 3
4 6 5 2 1
4 4 5 2 1
5 6 8 5 3'''
right_str = '''3 2 4 0
3 2 4 2
0 7 3 3
3 3 0 2
1 3 2 2'''

down = np.fromstring(down_str, int, sep = ' ').reshape(n,m+1)
right = np.fromstring(right_str, int, sep = ' ').reshape(n+1,m)
print(down, right)
longest_path(n,m,down, right)

[[1 0 2 4 3]
 [4 6 5 2 1]
 [4 4 5 2 1]
 [5 6 8 5 3]] [[3 2 4 0]
 [3 2 4 2]
 [0 7 3 3]
 [3 3 0 2]
 [1 3 2 2]]
[[ 0  3  5  9  9]
 [ 1  0  0  0  0]
 [ 5  0  0  0  0]
 [ 9  0  0  0  0]
 [14  0  0  0  0]]


34

## BA5C

### LCS of 2 strings 

In [52]:
import numpy as np

def lcs(u, v):
    n, m = len(u), len(v)
    scores = np.zeros([n+1, m+1], dtype = int)
#     scores = [[0]*(m+1) for _ in range(n+1)]
#     print(scores)
    pointers = np.zeros([n+1, m+1], dtype = int)
    
    for i in range(1,n+1):
        for j in range(1,m+1):
            scores[i][j] = max((scores[i-1][j-1] + (1 if u[i-1] == v[i-1] else 0), (i-1,j-1)), (scores[i][j-1], (i-1,j)))
            pointers[i][j] = (scores[i-1][j], (i,j-1)), (scores[i-1][j], (i-1,j))
    
    def backtrack_iterative(i,j):
        output = ''
        while i>0 and j>0:
            if i-pointers[i][j][0] === j-pointers[i][j][1]
                output = u[i-1] + output 
                i,j = 
 
u = 'AACCTTGG'
v = 'ACACTGTGA'
lcs(u,v)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
